---
title: "Secondary Dataset"
output: html_document
---

```{r}
#upload relevant packages and data
rm(list = ls())
library(limma)
library(Glimma)
library(edgeR)
library(network)
library(RColorBrewer)

counts_files <- read.delim("C:/Users/weida/Desktop/20.440/Project/New data/GSE101521_totalRNA_counts.txt",row.names=1)
#specify what region of the brain you want to analyze
count_file = counts_files[1:59]
```

```{r}
#Sample Characterisics
#group <- c('CON','CON', 'CON',	'CON', 'CON',	'CON',	'CON', 'CON', 'CON)', 'MDD-S',	'CON',	'CON',	'CON',	'CON', 'MDD-S',	'MDD-S', 'CON', 'MDD-S', 'MDD-S', 'MDD-S',	'MDD-S',	'MDD-S',	'MDD-S',	'MDD-S','CON','MDD-S','CON', 'MDD-S','CON','CON','MDD-S','CON','CON','CON','MDD','MDD','MDD','MDD-S','CON','MDD',	'MDD-S','CON', 'CON',	'CON', 'MDD',	'CON','MDD','MDD-S','MDD', 'MDD-S', 'MDD-S', 'CON', 'MDD','MDD-S','MDD-S', 'MDD-S','MDD','CON','CON')

group = c('M_CON','F_CON','M_CON','M_CON','M_CON','M_CON','M_CON','M_CON','F_CON','F_MDD_S','M_CON','M_CON','M_CON','M_CON','M_MDD_S','M_MDD_S','M_CON','M_MDD_S','F_MDD_S','M_MDD_S','F_MDD_S','F_MDD_S','M_MDD_S','M_MDD_S','M_CON','M_MDD_S','M_CON','F_MDD_S','M_CON','M_CON','M_MDD_S','M_CON','M_CON','F_CON','M_MDD','M_MDD','M_MDD','M_MDD_S','M_CON','M_MDD','M_MDD_S','F_CON','M_CON','M_CON','M_MDD','M_CON','M_MDD','F_MDD_S','F_MDD','M_MDD_S','M_MDD_S','F_CON','F_MDD','F_MDD_S','F_MDD_S','M_MDD_S','F_MDD','M_CON','F_CON')

sex <- c('M','F','M','M','M','M','M','M','F','F','M','M','M','M','M','M','M','M','F','M','F','F', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M','M','M','F','M','M','M','M','M','F','F','M','M','F','F','F','F','M','F','M','F')

samples <- data.frame('group'=group,'sex'=sex)
genes <- rownames(counts_files)
genes <- data.frame('genes'=genes)
```

```{r}
#develop a DGE list
DGE_data2 <-DGEList(counts = count_file, samples = samples, group = group, genes = genes, remove.zeros = TRUE)
```
```{r}
cpm <- cpm(count_file)
lcpm <- cpm(count_file, log=TRUE)
```

```{r}
#MDS of Data before any limma
col.group <- group
levels(col.group) <-  brewer.pal(nlevels(col.group), "Set1")

col.sex <- sex
levels(col.sex) <-  brewer.pal(nlevels(col.sex), "Set2")

par(mar=c(6,4,4,2)+.1)
mds2 <- plotMDS(lcpm, labels=sex)
plot(mds2,xlab=NA, ylab=NA,pch =16,col = as.color(sex))
title(main="Male vs. Female",xlab="MDS 1", ylab="MDS 2")
```
```{r}
#design <- model.matrix(~0+sex:group)
design <- model.matrix(~0+group)
#covar <- model.matrix(~0+age+aINS_RIN+alcohol+medic)
#design <- model.matrix(~0+group+age+aINS_RIN+alcohol+medic)
#design <- cbind(design,covar)
#x <- c("F_CTRL","M_CTRL","F_MDD","M_MDD","age","aINS_RIN","alcoholNA","alcoholno","alcoholNo","alcoholyes", "medicno","medicyes")
#colnames(design) <- gsub("group", "", x)
contr.matrix <- makeContrasts(
     M_MDDvsCTRL = groupM_MDD - groupM_CON, 
     #F_MDDvsCTRL = "groupF_MDD - groupF_CON", 
     levels = design)
```

```{r}
keep <- filterByExpr(DGE_data2 , design) 
deg  <- DGE_data2[keep,,keep.lib.sizes=FALSE]
deg <- calcNormFactors(deg)
#for (val in colnames(deg)){
  #deg$val <- calcNormFactors(deg$val)
#}
```

```{r}
write.csv(deg[["counts"]],file="filtered_expression_data.csv")
```

```{r}
v <- voom(deg, design, plot=TRUE)
fit <- lmFit(v, design)
vfit <- contrasts.fit(fit, contrasts=contr.matrix)
efit <- eBayes(vfit, trend = TRUE)
#efit <- treat(efit, lfc=log2(1.2))
plotSA(efit, main="Final model: Mean-variance trend")

```

```{r}
summary(decideTests(efit))
result <- topTable(efit, coef=1, number=Inf,adjust.method="none",sort.by="logFC", p.value=0.05, confint=FALSE)
write.csv(result,file="result_M.csv")
```

